<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Example test run" duration-ms="21783" started-at="2017-06-14T11:36:33Z" finished-at="2017-06-14T11:36:55Z">
    <groups>
    </groups>
    <test name="testgit" duration-ms="21783" started-at="2017-06-14T11:36:33Z" finished-at="2017-06-14T11:36:55Z">
      <class name="test.test.testgit">
        <test-method status="PASS" signature="browserlaunch()[pri:0, instance:test.test.testgit@286778]" name="browserlaunch" is-config="true" duration-ms="11629" started-at="2017-06-14T17:06:33Z" finished-at="2017-06-14T17:06:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- browserlaunch -->
        <test-method status="FAIL" signature="test()[pri:0, instance:test.test.testgit@286778]" name="test" duration-ms="9079" started-at="2017-06-14T17:06:45Z" finished-at="2017-06-14T17:06:54Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Uma] but found [uma]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Uma] but found [uma]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at test.test.testgit.test(testgit.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:test.test.testgit@286778]" name="teardown" is-config="true" duration-ms="1041" started-at="2017-06-14T17:06:54Z" finished-at="2017-06-14T17:06:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- test.test.testgit -->
    </test> <!-- testgit -->
  </suite> <!-- Example test run -->
</testng-results>
